# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/accounts/, role: ROLE_ADMIN }
        - { path: ^/carts/, role: ROLE_ADMIN }
        - { path: ^/categories/, role: ROLE_ADMIN }
        - { path: ^/communicationMethods/, role: ROLE_ADMIN }
        - { path: ^/deliveryMethods/, role: ROLE_ADMIN }
        - { path: ^/eventLogs/, role: ROLE_ADMIN }
        - { path: ^/images/, role: ROLE_ADMIN }
        - { path: ^/orders/, role: ROLE_ADMIN }
        - { path: ^/paymentMethods/, role: ROLE_ADMIN }
        - { path: ^/products/, role: ROLE_ADMIN }
        - { path: ^/reviews/, role: ROLE_ADMIN }
        - { path: ^/schedules/, role: ROLE_ADMIN }
        - { path: ^/services/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_ADMIN }
        - { path: ^/zipCodes/, role: ROLE_ADMIN }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
