<?php

namespace ORFS\Bundle\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZipCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCodesRepository extends EntityRepository
{
}
